<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { createIssue, listEligibleProjects, listParts, type InventoryPart, type ProjectOption } from "@/api/inventory";
import { useAuthStore } from "@/stores/auth";
import { createOperationId } from "@/utils/offline";

const auth=useAuthStore();const parts=ref<InventoryPart[]>([]);const projects=ref<ProjectOption[]>([]);const lines=ref<Array<{partId:string;quantity:number}>>([]);const saving=ref(false);
const draft=reactive({partId:"",quantity:1});const form=reactive({projectId:"",issueDate:new Date().toISOString().slice(0,10),purpose:""});
const projectIndex=computed(()=>Math.max(0,projects.value.findIndex(i=>i.id===form.projectId)));const partIndex=computed(()=>Math.max(0,parts.value.findIndex(i=>i.id===draft.partId)));
function addLine(){if(!draft.partId||draft.quantity<=0){uni.showToast({title:"请选择备件并填写数量",icon:"none"});return;}if(lines.value.some(i=>i.partId===draft.partId)){uni.showToast({title:"该备件已添加",icon:"none"});return;}lines.value.push({partId:draft.partId,quantity:Number(draft.quantity)});draft.partId="";draft.quantity=1;}
async function submit(){if(!form.projectId||!form.purpose.trim()||!lines.value.length){uni.showToast({title:"请完整填写领用信息",icon:"none"});return;}saving.value=true;try{await createIssue({code:createOperationId("MBISS").slice(0,40),projectId:form.projectId,issueDate:form.issueDate,receiverName:auth.user?.displayName||auth.user?.username,purpose:form.purpose.trim(),lines:lines.value});uni.showToast({title:"领用已出库",icon:"success"});setTimeout(()=>uni.navigateBack(),700);}catch(e){uni.showToast({title:(e as Error).message,icon:"none"});}finally{saving.value=false;}}
onMounted(async()=>{try{[parts.value,projects.value]=await Promise.all([listParts(),listEligibleProjects()]);}catch(e){uni.showToast({title:(e as Error).message,icon:"none"});}});
</script>

<template><view class="page-shell form-page"><view class="surface form-card"><view class="field"><text class="field-label">归属项目 *</text><picker :range="projects" range-key="name" :value="projectIndex" @change="form.projectId=projects[Number(($event.detail as any).value)].id"><view class="field-picker">{{ form.projectId?projects[projectIndex]?.name:"请选择项目" }}</view></picker></view><view class="field"><text class="field-label">领用日期 *</text><picker mode="date" :value="form.issueDate" @change="form.issueDate=String(($event.detail as any).value)"><view class="field-picker">{{ form.issueDate }}</view></picker></view><view class="field"><text class="field-label">用途 *</text><textarea v-model="form.purpose" class="field-textarea small" maxlength="300" placeholder="说明关联工单及用途" /></view></view><view class="surface form-card"><text class="section-title">领用明细</text><view v-for="(line,index) in lines" :key="line.partId" class="line"><text>{{ parts.find(i=>i.id===line.partId)?.name }}</text><text>× {{ line.quantity }}</text><uni-icons type="trash" size="18" color="#b53232" @click="lines.splice(index,1)" /></view><view class="line-draft"><picker :range="parts" range-key="name" :value="partIndex" @change="draft.partId=parts[Number(($event.detail as any).value)].id"><view class="field-picker">{{ draft.partId?parts[partIndex]?.name:"选择备件" }}</view></picker><input v-model.number="draft.quantity" class="field-input" type="digit" placeholder="数量" /><button @click="addLine">添加</button></view></view><button class="primary-btn" :disabled="saving" @click="submit">{{ saving?"正在提交":"确认领用出库" }}</button></view></template>

<style scoped>.form-page{padding-top:24rpx}.form-card{padding:28rpx;margin-bottom:18rpx}.field-textarea.small{min-height:120rpx}.line{min-height:72rpx;display:grid;grid-template-columns:1fr auto 40rpx;gap:12rpx;align-items:center;border-bottom:1rpx solid #edf0f1;font-size:24rpx}.line-draft{margin-top:20rpx;display:grid;grid-template-columns:1.5fr .65fr .55fr;gap:10rpx}.line-draft .field-picker,.line-draft .field-input{min-height:70rpx;height:70rpx;font-size:23rpx}.line-draft button{height:70rpx;line-height:70rpx;padding:0;color:#176b5b;background:#e4f0ed;border-radius:9rpx;font-size:23rpx}</style>
