<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { createReturn, listIssues, type MaterialIssue } from "@/api/inventory";
import { useAuthStore } from "@/stores/auth";
import { createOperationId } from "@/utils/offline";

const auth=useAuthStore();const issues=ref<MaterialIssue[]>([]);const selected=ref<MaterialIssue|null>(null);const quantities=reactive<Record<string,number>>({});const reason=ref("");const saving=ref(false);
const available=computed(()=>issues.value.filter(i=>i.lines.some(l=>Number(l.returnableQty)>0)));const issueIndex=computed(()=>Math.max(0,available.value.findIndex(i=>i.id===selected.value?.id)));
function selectIssue(index:number){selected.value=available.value[index]||null;Object.keys(quantities).forEach(k=>delete quantities[k]);}
async function submit(){if(!selected.value||!reason.value.trim()){uni.showToast({title:"请选择领料单并填写原因",icon:"none"});return;}const lines=selected.value.lines.filter(l=>Number(quantities[l.id]||0)>0).map(l=>({issueLineId:l.id,quantity:Number(quantities[l.id])}));if(!lines.length){uni.showToast({title:"请填写至少一项归还数量",icon:"none"});return;}if(lines.some(line=>line.quantity>Number(selected.value!.lines.find(l=>l.id===line.issueLineId)?.returnableQty||0))){uni.showToast({title:"归还数量超过可退数量",icon:"none"});return;}saving.value=true;try{await createReturn(selected.value.id,{code:createOperationId("MBRET").slice(0,40),returnDate:new Date().toISOString().slice(0,10),handlerName:auth.user?.displayName||auth.user?.username,reason:reason.value.trim(),lines});uni.showToast({title:"备件已归还",icon:"success"});setTimeout(()=>uni.navigateBack(),700);}catch(e){uni.showToast({title:(e as Error).message,icon:"none"});}finally{saving.value=false;}}
onMounted(async()=>{try{issues.value=await listIssues();}catch(e){uni.showToast({title:(e as Error).message,icon:"none"});}});
</script>

<template><view class="page-shell form-page"><view class="surface form-card"><view class="field"><text class="field-label">原领料单 *</text><picker :range="available" range-key="code" :value="issueIndex" @change="selectIssue(Number(($event.detail as any).value))"><view class="field-picker">{{ selected?`${selected.code} · ${selected.projectName}`:"请选择可退领料单" }}</view></picker></view><view class="field"><text class="field-label">归还原因 *</text><textarea v-model="reason" class="field-textarea small" maxlength="255" placeholder="说明剩余、错领或更换原因" /></view></view><view v-if="selected" class="surface form-card"><text class="section-title">归还明细</text><view v-for="line in selected.lines.filter(i=>Number(i.returnableQty)>0)" :key="line.id" class="return-line"><view><text>{{ line.partName }}</text><text>已领 {{ line.quantity }} · 可退 {{ line.returnableQty }}</text></view><input v-model.number="quantities[line.id]" type="digit" placeholder="归还数" /></view></view><view v-else-if="!available.length" class="empty-state surface">暂无可归还的领料单</view><button class="primary-btn" :disabled="saving||!selected" @click="submit">{{ saving?"正在提交":"确认归还入库" }}</button></view></template>

<style scoped>.form-page{padding-top:24rpx}.form-card{padding:28rpx;margin-bottom:18rpx}.field-textarea.small{min-height:120rpx}.return-line{min-height:100rpx;display:grid;grid-template-columns:1fr 150rpx;gap:20rpx;align-items:center;border-bottom:1rpx solid #edf0f1}.return-line text{display:block}.return-line text:first-child{font-weight:650}.return-line text:last-child{margin-top:7rpx;color:#7b848d;font-size:21rpx}.return-line input{height:70rpx;padding:0 14rpx;text-align:center;border:1rpx solid #dfe5e7;border-radius:8rpx;background:#f8fafb}</style>
