package com.company.ops.api.modules.procurement.service;
import com.company.ops.api.common.exception.BusinessException;
import com.company.ops.api.common.service.CodeGenerator;
import com.company.ops.api.modules.inventory.domain.*; import com.company.ops.api.modules.inventory.repository.*;
import com.company.ops.api.modules.procurement.domain.*; import com.company.ops.api.modules.procurement.dto.ProcurementControlDtos.*; import com.company.ops.api.modules.procurement.repository.*;
import java.math.*; import java.time.OffsetDateTime; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.company.ops.api.modules.system.security.UserPrincipal; import org.springframework.security.core.context.SecurityContextHolder;
@Service
public class ProcurementControlService {
 private final CodeGenerator codes; private final ProcurementInquiryRepository inquiries; private final SupplierQuotationRepository quotes;
 private final PurchaseRequestRepository requests; private final SupplierRepository suppliers; private final PurchaseOrderRepository orders;
 private final GoodsReceiptRepository receipts; private final InventoryPartRepository parts; private final StockMovementRepository movements;
 private final ProcurementPayableRepository payables; private final ProcurementCostAllocationRepository costs; private final ProcurementReturnOrderRepository returns;
 private final SupplierInvoiceRepository invoices;
 public ProcurementControlService(CodeGenerator c,ProcurementInquiryRepository i,SupplierQuotationRepository q,PurchaseRequestRepository r,SupplierRepository s,PurchaseOrderRepository o,GoodsReceiptRepository gr,InventoryPartRepository p,StockMovementRepository m,ProcurementPayableRepository py,ProcurementCostAllocationRepository co,ProcurementReturnOrderRepository ro,SupplierInvoiceRepository si){codes=c;inquiries=i;quotes=q;requests=r;suppliers=s;orders=o;receipts=gr;parts=p;movements=m;payables=py;costs=co;returns=ro;invoices=si;}
 @Transactional(readOnly=true) public List<Map<String,Object>> listInquiries(){return inquiries.findAllByOrderByCreatedAtDesc().stream().map(this::inquiryView).toList();}
 @Transactional public Map<String,Object> createInquiry(CreateInquiry x){PurchaseRequest r=requests.findById(x.requestId()).orElseThrow(()->new BusinessException("采购申请不存在")); if(r.getApprovalStatus()!=ApprovalStatus.APPROVED)throw new BusinessException("采购申请审批通过后才能询价"); ProcurementInquiry i=new ProcurementInquiry();i.setCode("XJ-"+System.currentTimeMillis());i.setRequestId(r.getId());i.setTitle(x.title());i.setDeadline(x.deadline());i.setCreatedByName(currentName());i.setStatus("OPEN");return inquiryView(inquiries.save(i));}
 @Transactional public Map<String,Object> addQuote(UUID id,CreateSupplierQuote x){ProcurementInquiry i=inquiries.findById(id).orElseThrow(()->new BusinessException("询价单不存在"));if(!"OPEN".equals(i.getStatus()))throw new BusinessException("询价已结束");Supplier s=suppliers.findById(x.supplierId()).orElseThrow(()->new BusinessException("供应商不存在"));if(s.getRiskStatus()==SupplierRiskStatus.BLOCKED)throw new BusinessException("冻结供应商不能报价");SupplierQuotation q=new SupplierQuotation();q.setInquiryId(id);q.setSupplierId(x.supplierId());q.setUnitPrice(x.unitPrice());q.setTaxRate(x.taxRate());q.setDeliveryDate(x.deliveryDate());q.setPaymentTerms(x.paymentTerms());q.setRemark(x.remark());quotes.save(q);return quoteView(q);}
 @Transactional public Map<String,Object> selectQuote(UUID id,UUID quoteId,SelectSupplierQuote x){ProcurementInquiry i=inquiries.findById(id).orElseThrow(()->new BusinessException("询价单不存在"));SupplierQuotation selected=quotes.findById(quoteId).orElseThrow(()->new BusinessException("供应商报价不存在"));if(!selected.getInquiryId().equals(id))throw new BusinessException("报价不属于该询价单");quotes.findByInquiryIdOrderByUnitPriceAsc(id).forEach(q->{q.setSelected(q.getId().equals(quoteId));quotes.save(q);});i.setStatus("AWARDED");inquiries.save(i);return inquiryView(i);}
 private Map<String,Object> inquiryView(ProcurementInquiry i){Map<String,Object> m=new LinkedHashMap<>();m.put("id",i.getId());m.put("code",i.getCode());m.put("requestId",i.getRequestId());m.put("title",i.getTitle());m.put("deadline",i.getDeadline());m.put("status",i.getStatus());m.put("createdByName",i.getCreatedByName());m.put("quotes",quotes.findByInquiryIdOrderByUnitPriceAsc(i.getId()).stream().map(this::quoteView).toList());return m;}
 private Map<String,Object> quoteView(SupplierQuotation q){Supplier s=suppliers.findById(q.getSupplierId()).orElse(null);Map<String,Object> m=new LinkedHashMap<>();m.put("id",q.getId());m.put("supplierId",q.getSupplierId());m.put("supplierName",s==null?null:s.getName());m.put("unitPrice",q.getUnitPrice());m.put("taxRate",q.getTaxRate());m.put("deliveryDate",q.getDeliveryDate());m.put("paymentTerms",q.getPaymentTerms());m.put("remark",q.getRemark());m.put("selected",q.isSelected());return m;}
 @Transactional public GoodsReceipt registerArrival(UUID orderId,com.company.ops.api.modules.procurement.dto.ReceivePurchaseOrderRequest x){PurchaseOrder o=orders.findByIdForUpdate(orderId).orElseThrow(()->new BusinessException("采购订单不存在"));if(o.getStatus()!=PurchaseOrderStatus.ORDERED&&o.getStatus()!=PurchaseOrderStatus.PARTIAL_RECEIVED)throw new BusinessException("只有审批通过的订单可以登记到货");BigDecimal pending=receipts.findAllByOrderByReceivedDateDesc().stream().filter(r->r.getOrderId().equals(orderId)&&"PENDING".equals(r.getInspectionStatus())).map(GoodsReceipt::getQuantity).reduce(BigDecimal.ZERO,BigDecimal::add);if(o.getReceivedQty().add(pending).add(x.quantity()).compareTo(o.getOrderedQty())>0)throw new BusinessException("到货数量超过订单剩余数量");GoodsReceipt r=new GoodsReceipt();r.setCode("DH-"+o.getCode()+"-"+String.format("%02d",receipts.countByOrderId(orderId)+1));r.setOrderId(orderId);r.setPartId(o.getPartId());r.setQuantity(x.quantity());r.setUnitPrice(o.getUnitPrice());r.setTaxRate(o.getTaxRate());r.setAmount(x.quantity().multiply(o.getUnitPrice()));r.setReceivedDate(x.receivedDate());r.setDeliveryNo(x.deliveryNo());r.setReceiverName(currentName());r.setPayableDueDate(x.payableDueDate());r.setInspectionStatus("PENDING");return receipts.save(r);}
 @Transactional public Map<String,Object> inspect(UUID receiptId,InspectReceipt x){GoodsReceipt r=receipts.findById(receiptId).orElseThrow(()->new BusinessException("到货记录不存在"));if(!"PENDING".equals(r.getInspectionStatus()))throw new BusinessException("该到货记录已质检");if(x.qualifiedQty().add(x.rejectedQty()).compareTo(r.getQuantity())!=0)throw new BusinessException("合格与不合格数量合计必须等于到货数量");PurchaseOrder o=orders.findByIdForUpdate(r.getOrderId()).orElseThrow(()->new BusinessException("订单不存在"));String operator=currentName();r.setQualifiedQty(x.qualifiedQty());r.setRejectedQty(x.rejectedQty());r.setInspectorName(operator);r.setInspectionComment(x.comment());r.setInspectedAt(OffsetDateTime.now());r.setInspectionStatus(x.rejectedQty().signum()==0?"PASSED":x.qualifiedQty().signum()==0?"REJECTED":"PARTIAL");r.setPayableDueDate(x.payableDueDate());receipts.save(r);
  if(x.qualifiedQty().signum()>0){InventoryPart p=parts.findById(o.getPartId()).orElseThrow(()->new BusinessException("物料不存在"));BigDecimal old=p.getStockQty(), after=old.add(x.qualifiedQty());p.setStockQty(after);p.setUnitCost(old.multiply(p.getUnitCost()).add(x.qualifiedQty().multiply(o.getUnitPrice())).divide(after,2,RoundingMode.HALF_UP));parts.save(p);StockMovement sm=new StockMovement();sm.setPartId(p.getId());sm.setMovementType(StockMovementType.INBOUND);sm.setQuantity(x.qualifiedQty());sm.setSourceNo(o.getCode());sm.setRemark("采购质检合格入库 "+r.getCode());movements.save(sm);BigDecimal amt=x.qualifiedQty().multiply(o.getUnitPrice());ProcurementPayable py=new ProcurementPayable();py.setCode("YF-"+r.getCode());py.setSupplierId(o.getSupplierId());py.setOrderId(o.getId());py.setReceiptId(r.getId());py.setAmount(amt);py.setTaxRate(o.getTaxRate());py.setPaidAmount(BigDecimal.ZERO);py.setDueDate(x.payableDueDate());py.setStatus(PayableStatus.PENDING);payables.save(py);ProcurementCostAllocation c=new ProcurementCostAllocation();c.setOrderId(o.getId());c.setReceiptId(r.getId());c.setCostType(o.getCostType());c.setProjectId(o.getProjectId());c.setDepartmentId(o.getDepartmentId());c.setTargetCode(o.getCostTargetCode());c.setTargetName(o.getCostTargetName());c.setPartName(o.getPartName());c.setAmount(amt);c.setIncurredDate(r.getReceivedDate());costs.save(c);o.setReceivedQty(o.getReceivedQty().add(x.qualifiedQty()));o.setStatus(o.getReceivedQty().compareTo(o.getOrderedQty())==0?PurchaseOrderStatus.RECEIVED:PurchaseOrderStatus.PARTIAL_RECEIVED);orders.save(o);}
  ProcurementReturnOrder ro=null;if(x.rejectedQty().signum()>0){ro=new ProcurementReturnOrder();ro.setCode("TH-"+r.getCode());ro.setOrderId(o.getId());ro.setReceiptId(r.getId());ro.setSupplierId(o.getSupplierId());ro.setQuantity(x.rejectedQty());ro.setAmount(x.rejectedQty().multiply(o.getUnitPrice()));ro.setReason(x.comment()==null?"质检不合格":x.comment());ro.setReturnDate(r.getReceivedDate());ro.setHandlerName(operator);returns.save(ro);}return Map.of("receipt",r,"order",o,"returnOrder",ro==null?Map.of():ro);}
 @Transactional(readOnly=true) public List<ProcurementReturnOrder> listReturns(){return returns.findAllByOrderByReturnDateDesc();}
 @Transactional public SupplierInvoice createInvoice(CreateInvoice x){if(invoices.existsByInvoiceNo(x.invoiceNo()))throw new BusinessException("供应商发票号码已存在");PurchaseOrder o=orders.findById(x.orderId()).orElseThrow(()->new BusinessException("订单不存在"));BigDecimal received=receipts.findAllByOrderByReceivedDateDesc().stream().filter(r->r.getOrderId().equals(o.getId())).map(r->Optional.ofNullable(r.getQualifiedQty()).orElse(BigDecimal.ZERO).multiply(r.getUnitPrice())).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal payable=payables.findAll().stream().filter(p->p.getOrderId().equals(o.getId())&&p.getStatus()!=PayableStatus.CANCELLED).map(ProcurementPayable::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal diff=x.amount().subtract(received);SupplierInvoice i=new SupplierInvoice();i.setCode("CGFP-"+System.currentTimeMillis());i.setInvoiceNo(x.invoiceNo());i.setOrderId(o.getId());i.setSupplierId(o.getSupplierId());i.setAmount(x.amount());i.setTaxRate(x.taxRate());i.setInvoiceDate(x.invoiceDate());i.setDifferenceAmount(diff);i.setMatchStatus(diff.signum()==0&&x.amount().compareTo(payable)==0&&x.amount().compareTo(o.getOrderAmount())<=0?"MATCHED":"MISMATCH");i.setRemark(x.remark());return invoices.save(i);}
 @Transactional(readOnly=true) public List<SupplierInvoice> listInvoices(){return invoices.findAllByOrderByInvoiceDateDesc();}
 private String currentName(){var a=SecurityContextHolder.getContext().getAuthentication();return a!=null&&a.getPrincipal() instanceof UserPrincipal p?p.displayName():"系统";}
}
