<template>
  <div class="page-stack">
    <a-card title="总账与财务报表"><template #extra><a-button :loading="loading" @click="loadData"><template #icon><ReloadOutlined /></template>刷新</a-button></template>
      <a-row :gutter="[16,16]" class="metric-row"><a-col :xs="12" :xl="4"><a-statistic title="记账凭证" :value="overview.voucherCount" suffix="张" /></a-col><a-col :xs="12" :xl="4"><a-statistic title="累计借方" :value="overview.totalDebit" :formatter="moneyFormatter" /></a-col><a-col :xs="12" :xl="4"><a-statistic title="营业收入" :value="overview.revenue" :formatter="moneyFormatter" /></a-col><a-col :xs="12" :xl="4"><a-statistic title="成本费用" :value="overview.expense" :formatter="moneyFormatter" /></a-col><a-col :xs="12" :xl="4"><a-statistic title="账面利润" :value="overview.profit" :formatter="moneyFormatter" :value-style="profitStyle" /></a-col><a-col :xs="12" :xl="4"><a-statistic title="银行净流量" :value="overview.cashBalance" :formatter="moneyFormatter" /></a-col></a-row>
    </a-card>
    <a-card><a-tabs v-model:active-key="activeTab"><a-tab-pane key="vouchers" tab="会计凭证"><a-table :columns="voucherColumns" :data-source="vouchers" :loading="loading" :pagination="{pageSize:8}" :row-key="(item:AccountingVoucher)=>item.id" :scroll="{x:1100}"><template #bodyCell="{column,record}"><template v-if="column.key==='voucher'"><a-button type="link" class="table-link" @click="openVoucher(record)">{{record.code}}</a-button><span class="table-subtitle">{{record.description}}</span></template><template v-else-if="column.key==='amount'">{{formatMoney(record.totalDebit)}}</template><template v-else-if="column.key==='status'"><a-tag :color="record.status==='POSTED'?'green':'default'">{{record.status==='POSTED'?'已记账':'已冲销'}}</a-tag></template><template v-else-if="column.key==='action'"><a-button type="link" size="small" @click="openVoucher(record)">查看分录</a-button></template></template></a-table></a-tab-pane>
      <a-tab-pane key="statements" tab="财务报表"><a-descriptions bordered :column="3" class="statement-summary"><a-descriptions-item label="资产合计">{{formatMoney(statements.totalAssets)}}</a-descriptions-item><a-descriptions-item label="负债合计">{{formatMoney(statements.totalLiabilities)}}</a-descriptions-item><a-descriptions-item label="本期利润"><strong :class="{'text-danger':statements.profit<0}">{{formatMoney(statements.profit)}}</strong></a-descriptions-item><a-descriptions-item label="营业收入">{{formatMoney(statements.totalRevenue)}}</a-descriptions-item><a-descriptions-item label="成本费用">{{formatMoney(statements.totalExpense)}}</a-descriptions-item><a-descriptions-item label="现金净流量">{{formatMoney(statements.netCashFlow)}}</a-descriptions-item></a-descriptions><a-row :gutter="[16,16]"><a-col :xs="24" :xl="12"><h3>资产负债表</h3><a-table size="small" :columns="statementColumns" :data-source="[...statements.assets,...statements.liabilities]" :pagination="false" :row-key="(item:StatementLine)=>item.accountCode"><template #bodyCell="{column,record}"><template v-if="column.key==='balance'">{{formatMoney(record.balance)}}</template></template></a-table></a-col><a-col :xs="24" :xl="12"><h3>利润表</h3><a-table size="small" :columns="statementColumns" :data-source="[...statements.revenue,...statements.expenses]" :pagination="false" :row-key="(item:StatementLine)=>item.accountCode"><template #bodyCell="{column,record}"><template v-if="column.key==='balance'">{{formatMoney(record.balance)}}</template></template></a-table></a-col></a-row></a-tab-pane></a-tabs></a-card>
    <a-drawer v-model:open="drawerOpen" title="会计凭证分录" width="680"><template v-if="selectedVoucher"><a-descriptions bordered :column="2" size="small"><a-descriptions-item label="凭证号">{{selectedVoucher.code}}</a-descriptions-item><a-descriptions-item label="日期">{{selectedVoucher.voucherDate}}</a-descriptions-item><a-descriptions-item label="业务来源">{{selectedVoucher.bizType}} · {{selectedVoucher.bizNo}}</a-descriptions-item><a-descriptions-item label="借贷合计">{{formatMoney(selectedVoucher.totalDebit)}}</a-descriptions-item><a-descriptions-item label="摘要" :span="2">{{selectedVoucher.description}}</a-descriptions-item></a-descriptions><a-divider /><a-table size="small" :columns="entryColumns" :data-source="selectedVoucher.entries" :pagination="false" :row-key="(item:VoucherEntry)=>item.id"><template #bodyCell="{column,record}"><template v-if="column.key==='debit'">{{record.debit?formatMoney(record.debit):'-'}}</template><template v-else-if="column.key==='credit'">{{record.credit?formatMoney(record.credit):'-'}}</template></template></a-table></template></a-drawer>
  </div>
</template>
<script setup lang="ts">
import{computed,onMounted,reactive,ref}from"vue";import{message}from"ant-design-vue";import ReloadOutlined from"@ant-design/icons-vue/ReloadOutlined";import{getFinancialStatements,getLedgerOverview,listVouchers,type AccountingVoucher,type FinancialStatements,type LedgerOverview,type StatementLine,type VoucherEntry}from"@/api/ledger";
const loading=ref(false),activeTab=ref("vouchers"),drawerOpen=ref(false),vouchers=ref<AccountingVoucher[]>([]),selectedVoucher=ref<AccountingVoucher|null>(null);const overview=reactive<LedgerOverview>({voucherCount:0,totalDebit:0,totalCredit:0,revenue:0,expense:0,profit:0,cashBalance:0});const statements=reactive<FinancialStatements>({assets:[],liabilities:[],revenue:[],expenses:[],totalAssets:0,totalLiabilities:0,totalRevenue:0,totalExpense:0,profit:0,netCashFlow:0});const profitStyle=computed(()=>overview.profit<0?{color:"#cf1322"}:{color:"#237804"});const voucherColumns=[{title:"凭证",key:"voucher",width:300},{title:"日期",dataIndex:"voucherDate",width:120},{title:"业务类型",dataIndex:"bizType",width:150},{title:"业务单号",dataIndex:"bizNo",width:190},{title:"借贷金额",key:"amount",width:160},{title:"状态",key:"status",width:100},{title:"操作",key:"action",width:120}];const statementColumns=[{title:"科目编码",dataIndex:"accountCode",width:100},{title:"科目名称",dataIndex:"accountName"},{title:"余额",key:"balance",width:150}];const entryColumns=[{title:"科目",dataIndex:"accountName"},{title:"摘要",dataIndex:"summary"},{title:"借方",key:"debit",width:140},{title:"贷方",key:"credit",width:140}];onMounted(loadData);async function loadData(){loading.value=true;try{const[o,v,s]=await Promise.all([getLedgerOverview(),listVouchers(),getFinancialStatements()]);Object.assign(overview,o);vouchers.value=v;Object.assign(statements,s);}catch(error){message.error(error instanceof Error?error.message:"总账数据加载失败");}finally{loading.value=false;}}function openVoucher(item:AccountingVoucher){selectedVoucher.value=item;drawerOpen.value=true;}function formatMoney(v:number){return new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY",minimumFractionDigits:2,maximumFractionDigits:2}).format(v||0);}function moneyFormatter(v:number|string){return formatMoney(Number(v));}
</script><style scoped>.statement-summary{margin-bottom:20px}h3{margin:8px 0 12px;font-size:16px}</style>
