<template>
  <div class="page-stack"><a-card title="采购控制中心"><template #extra><a-button :loading="loading" @click="load">刷新</a-button></template>
    <a-tabs v-model:activeKey="tab">
      <a-tab-pane key="inquiry" tab="询价比价"><a-button type="primary" @click="inquiryOpen=true">发起询价</a-button>
        <a-table style="margin-top:12px" :data-source="inquiries" :columns="inquiryColumns" row-key="id" :pagination="false">
          <template #expandedRowRender="{record}"><a-alert v-if="record.selectionReason" type="success" :message="`定标依据：${record.selectionReason}`" style="margin-bottom:8px"/><a-table size="small" :data-source="record.quotes" :columns="quoteColumns" row-key="id" :pagination="false"><template #bodyCell="{column,record:q}"><template v-if="column.key==='price'">{{money(q.unitPrice)}} + 运费 {{money(q.freightAmount)}} / 税率 {{q.taxRate}}%</template><template v-else-if="column.key==='score'">技术 {{q.technicalScore}} / 商务 {{q.commercialScore}} / <strong>{{q.totalScore}}</strong></template><template v-if="column.key==='select'"><a-button v-if="!q.selected&&record.status==='OPEN'" type="link" @click="selectQuote(record,q)">选定</a-button><a-tag v-else-if="q.selected" color="green">已选定</a-tag></template></template></a-table><a-button v-if="record.status==='OPEN'" size="small" @click="openQuote(record)">录入供应商报价</a-button></template>
          <template #bodyCell="{column,record}"><template v-if="column.key==='status'"><a-tag :color="record.status==='OPEN'?'blue':'green'">{{record.status==='OPEN'?'询价中':'已定标'}}</a-tag></template></template>
        </a-table></a-tab-pane>
      <a-tab-pane key="inspection" tab="到货质检"><a-table :data-source="pendingReceipts" :columns="receiptColumns" row-key="id"><template #bodyCell="{column,record}"><template v-if="column.key==='status'"><a-tag color="orange">待质检</a-tag></template><template v-if="column.key==='action'"><a-button type="link" @click="openInspect(record)">质检</a-button></template></template></a-table>
        <a-divider>退换货 / 索赔记录</a-divider><a-table size="small" :data-source="returns" :columns="returnColumns" row-key="id"><template #bodyCell="{column,record}"><template v-if="column.key==='amount'">{{money(record.amount)}}</template><template v-else-if="column.key==='status'"><a-tag :color="record.status==='COMPLETED'?'green':'orange'">{{record.status==='COMPLETED'?'已结案':'处理中'}}</a-tag></template><template v-else-if="column.key==='action'"><a-button v-if="record.status!=='COMPLETED'" type="link" @click="openResolve(record)">处理</a-button></template></template></a-table></a-tab-pane>
      <a-tab-pane key="invoice" tab="采购发票 / 四单匹配"><a-button type="primary" @click="invoiceOpen=true">登记供应商发票</a-button><a-table style="margin-top:12px" :data-source="invoices" :columns="invoiceColumns" row-key="id"><template #bodyCell="{column,record}"><template v-if="column.key==='amount'">{{money(record.amount)}}<span class="table-subtitle">已匹配 {{money(record.matchedAmount)}}</span></template><template v-else-if="column.key==='match'"><a-tag :color="record.matchStatus==='MATCHED'?'green':'red'">{{record.matchStatus==='MATCHED'?'订单·收货·应付·发票一致':'金额不符'}}</a-tag><span class="table-subtitle">差额 {{money(record.differenceAmount)}}</span></template><template v-else-if="column.key==='approval'"><a-tag :color="record.approvalStatus==='APPROVED'?'green':record.approvalStatus==='REJECTED'?'red':'orange'">{{record.approvalStatus==='APPROVED'?'已审核':record.approvalStatus==='REJECTED'?'已驳回':'待审核'}}</a-tag></template><template v-else-if="column.key==='action'"><a-button v-if="record.approvalStatus==='PENDING'&&record.matchStatus==='MATCHED'" type="link" @click="reviewInvoice(record,'APPROVED')">审核通过</a-button><a-button v-if="record.approvalStatus==='PENDING'" type="link" danger @click="reviewInvoice(record,'REJECTED')">驳回</a-button></template></template></a-table></a-tab-pane>
    </a-tabs></a-card>
    <a-modal v-model:open="inquiryOpen" title="发起询价" @ok="saveInquiry"><a-form layout="vertical"><a-form-item label="已审批采购申请"><a-select v-model:value="inquiryForm.requestId" :options="requestOptions" /></a-form-item><a-form-item label="询价主题"><a-input v-model:value="inquiryForm.title" /></a-form-item><a-row :gutter="12"><a-col :span="12"><a-form-item label="寻源方式"><a-select v-model:value="inquiryForm.sourcingMethod" :options="[{label:'竞争性询价',value:'COMPETITIVE'},{label:'单一来源',value:'SINGLE_SOURCE'},{label:'框架协议',value:'FRAMEWORK'}]" /></a-form-item></a-col><a-col :span="12"><a-form-item label="最低有效报价数"><a-input-number v-model:value="inquiryForm.minQuoteCount" :min="1" /></a-form-item></a-col></a-row><a-form-item v-if="inquiryForm.sourcingMethod==='SINGLE_SOURCE'" label="单一来源例外原因"><a-textarea v-model:value="inquiryForm.exceptionReason" /></a-form-item><a-form-item label="截止日期"><a-input v-model:value="inquiryForm.deadline" type="date" /></a-form-item></a-form></a-modal>
    <a-modal v-model:open="quoteOpen" title="录入供应商报价" @ok="saveQuote"><a-form layout="vertical"><a-form-item label="供应商"><a-select v-model:value="quoteForm.supplierId" :options="supplierOptions" /></a-form-item><a-row :gutter="12"><a-col :span="12"><a-form-item label="含税单价"><a-input-number v-model:value="quoteForm.unitPrice" :min="0.01" /></a-form-item></a-col><a-col :span="12"><a-form-item label="运费"><a-input-number v-model:value="quoteForm.freightAmount" :min="0" /></a-form-item></a-col></a-row><a-form-item label="税率"><a-input-number v-model:value="quoteForm.taxRate" :min="0" /></a-form-item><a-row :gutter="12"><a-col :span="12"><a-form-item label="技术评分"><a-input-number v-model:value="quoteForm.technicalScore" :min="0" :max="100" /></a-form-item></a-col><a-col :span="12"><a-form-item label="商务评分"><a-input-number v-model:value="quoteForm.commercialScore" :min="0" :max="100" /></a-form-item></a-col></a-row><a-form-item label="交付日期"><a-input v-model:value="quoteForm.deliveryDate" type="date" /></a-form-item><a-form-item label="报价有效期"><a-input v-model:value="quoteForm.validUntil" type="date" /></a-form-item><a-form-item label="付款条件"><a-input v-model:value="quoteForm.paymentTerms" /></a-form-item></a-form></a-modal>
    <a-modal v-model:open="inspectOpen" title="到货质检" @ok="saveInspection"><a-form layout="vertical"><a-alert v-if="selectedReceipt" :message="`到货数量 ${selectedReceipt.quantity}`"/><a-form-item label="合格数量"><a-input-number v-model:value="inspectForm.qualifiedQty" :min="0" /></a-form-item><a-form-item label="不合格数量"><a-input-number v-model:value="inspectForm.rejectedQty" :min="0" /></a-form-item><a-form-item label="质检人"><a-input v-model:value="inspectForm.inspectorName" /></a-form-item><a-form-item label="质检意见/退货原因"><a-textarea v-model:value="inspectForm.comment" /></a-form-item><a-form-item label="应付到期日"><a-input v-model:value="inspectForm.payableDueDate" type="date" /></a-form-item></a-form></a-modal>
    <a-modal v-model:open="invoiceOpen" title="登记供应商发票" @ok="saveInvoice"><a-form layout="vertical"><a-form-item label="采购订单"><a-select v-model:value="invoiceForm.orderId" :options="orderOptions" /></a-form-item><a-form-item label="关联应付（支持分批发票）"><a-select v-model:value="invoiceForm.payableId" allow-clear :options="payableOptions" /></a-form-item><a-form-item label="发票号码"><a-input v-model:value="invoiceForm.invoiceNo" /></a-form-item><a-form-item label="发票金额"><a-input-number v-model:value="invoiceForm.amount" :min="0.01" /></a-form-item><a-form-item label="税率"><a-input-number v-model:value="invoiceForm.taxRate" :min="0" /></a-form-item><a-form-item label="发票日期"><a-input v-model:value="invoiceForm.invoiceDate" type="date" /></a-form-item></a-form></a-modal>
    <a-modal v-model:open="resolveOpen" title="退换货 / 索赔结案" @ok="saveResolution"><a-form layout="vertical"><a-row :gutter="12"><a-col :span="8"><a-form-item label="补货数量"><a-input-number v-model:value="resolveForm.replacementQty" :min="0" /></a-form-item></a-col><a-col :span="8"><a-form-item label="红字/抵扣金额"><a-input-number v-model:value="resolveForm.creditAmount" :min="0" /></a-form-item></a-col><a-col :span="8"><a-form-item label="索赔金额"><a-input-number v-model:value="resolveForm.claimAmount" :min="0" /></a-form-item></a-col></a-row><a-form-item label="供应商反馈"><a-textarea v-model:value="resolveForm.supplierResponse" /></a-form-item><a-form-item label="纠正预防措施（CAPA）"><a-textarea v-model:value="resolveForm.correctiveAction" /></a-form-item></a-form></a-modal>
  </div>
</template>
<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'; import {message,Modal} from 'ant-design-vue'; import {useAuthStore} from '@/stores/auth'; import * as api from '@/api/procurement';
const auth=useAuthStore(),tab=ref('inquiry'),loading=ref(false),inquiries=ref<api.ProcurementInquiry[]>([]),receipts=ref<api.GoodsReceipt[]>([]),returns=ref<api.ProcurementReturnOrder[]>([]),invoices=ref<api.SupplierInvoice[]>([]),requests=ref<api.PurchaseRequest[]>([]),suppliers=ref<api.Supplier[]>([]),orders=ref<api.PurchaseOrder[]>([]),payables=ref<api.ProcurementPayable[]>([]);
const inquiryOpen=ref(false),quoteOpen=ref(false),inspectOpen=ref(false),invoiceOpen=ref(false),resolveOpen=ref(false),selectedInquiry=ref<api.ProcurementInquiry|null>(null),selectedReceipt=ref<api.GoodsReceipt|null>(null),selectedReturn=ref<api.ProcurementReturnOrder|null>(null);
const today=()=>new Date().toISOString().slice(0,10); const inquiryForm=reactive({requestId:'',title:'',deadline:'',createdByName:'',sourcingMethod:'COMPETITIVE',minQuoteCount:3,exceptionReason:''}),quoteForm=reactive({supplierId:'',unitPrice:0,taxRate:13,deliveryDate:'',paymentTerms:'',currency:'CNY',freightAmount:0,otherCostAmount:0,technicalScore:100,commercialScore:100,validUntil:''}),inspectForm=reactive({qualifiedQty:0,rejectedQty:0,inspectorName:'',comment:'',payableDueDate:today()}),invoiceForm=reactive({orderId:'',payableId:undefined as string|undefined,invoiceNo:'',amount:0,taxRate:13,invoiceDate:today(),clientRequestId:''}),resolveForm=reactive({replacementQty:0,creditAmount:0,claimAmount:0,correctiveAction:'',supplierResponse:'',handlerName:''});
const inquiryColumns=[{title:'询价单',dataIndex:'code'},{title:'主题',dataIndex:'title'},{title:'寻源方式',dataIndex:'sourcingMethod'},{title:'截止日',dataIndex:'deadline'},{title:'报价数',customRender:({record}:any)=>`${record.quotes.length}/${record.minQuoteCount}`},{title:'状态',key:'status'}],quoteColumns=[{title:'供应商',dataIndex:'supplierName'},{title:'报价',key:'price'},{title:'综合评分',key:'score'},{title:'交期',dataIndex:'deliveryDate'},{title:'付款条件',dataIndex:'paymentTerms'},{title:'操作',key:'select'}],receiptColumns=[{title:'到货单',dataIndex:'code'},{title:'订单',dataIndex:'orderCode'},{title:'物料',dataIndex:'partName'},{title:'数量',dataIndex:'quantity'},{title:'状态',key:'status'},{title:'操作',key:'action'}],returnColumns=[{title:'退货单',dataIndex:'code'},{title:'数量',dataIndex:'quantity'},{title:'金额',key:'amount'},{title:'原因',dataIndex:'reason'},{title:'日期',dataIndex:'returnDate'},{title:'状态',key:'status'},{title:'操作',key:'action'}],invoiceColumns=[{title:'发票号码',dataIndex:'invoiceNo'},{title:'订单',dataIndex:'orderId'},{title:'金额',key:'amount'},{title:'开票日期',dataIndex:'invoiceDate'},{title:'匹配',key:'match'},{title:'审核',key:'approval'},{title:'操作',key:'action'}];
const pendingReceipts=computed(()=>receipts.value.filter(x=>x.inspectionStatus==='PENDING')),requestOptions=computed(()=>requests.value.filter(x=>x.approvalStatus==='APPROVED'&&x.status==='APPROVED').map(x=>({label:`${x.code} · ${x.partName}`,value:x.id}))),supplierOptions=computed(()=>suppliers.value.filter(x=>x.admissionStatus==='APPROVED'&&x.riskStatus!=='BLOCKED').map(x=>({label:x.name,value:x.id}))),orderOptions=computed(()=>orders.value.filter(x=>x.approvalStatus==='APPROVED').map(x=>({label:`${x.code} · ${x.supplierName}`,value:x.id}))),payableOptions=computed(()=>payables.value.filter(x=>!invoiceForm.orderId||x.orderId===invoiceForm.orderId).map(x=>({label:`${x.code} · 待付 ${money(x.outstandingAmount)}`,value:x.id})));
onMounted(load); async function load(){loading.value=true;try{const [iq,gr,rt,iv,pr,sp,po,py]=await Promise.all([api.listProcurementInquiries(),api.listGoodsReceipts(),api.listProcurementReturns(),api.listSupplierInvoices(),api.listPurchaseRequests({page:0,size:999}),api.listSuppliers(0,999),api.listPurchaseOrders({page:0,size:999}),api.listProcurementPayables()]);inquiries.value=iq;receipts.value=gr;returns.value=rt;invoices.value=iv;requests.value=pr.content;suppliers.value=sp.content;orders.value=po.content;payables.value=py;}catch(e){message.error(e instanceof Error?e.message:'加载失败')}finally{loading.value=false}}
function openQuote(x:api.ProcurementInquiry){selectedInquiry.value=x;quoteOpen.value=true} function openInspect(x:api.GoodsReceipt){selectedReceipt.value=x;Object.assign(inspectForm,{qualifiedQty:Number(x.quantity),rejectedQty:0,inspectorName:auth.user?.displayName||'',comment:'',payableDueDate:today()});inspectOpen.value=true} function openResolve(x:api.ProcurementReturnOrder){selectedReturn.value=x;Object.assign(resolveForm,{replacementQty:x.quantity,creditAmount:0,claimAmount:0,correctiveAction:'',supplierResponse:'',handlerName:auth.user?.displayName||''});resolveOpen.value=true}
async function saveInquiry(){inquiryForm.createdByName=auth.user?.displayName||'采购员';await api.createProcurementInquiry({...inquiryForm});inquiryOpen.value=false;await load()} async function saveQuote(){if(!selectedInquiry.value)return;await api.addSupplierQuotation(selectedInquiry.value.id,{...quoteForm});quoteOpen.value=false;await load()} async function selectQuote(i:api.ProcurementInquiry,q:api.SupplierQuotation){Modal.confirm({title:`选定 ${q.supplierName}？`,content:`单价 ${money(q.unitPrice)}，综合评分 ${q.totalScore}`,async onOk(){await api.selectSupplierQuotation(i.id,q.id,{operatorName:auth.user?.displayName||'审批人',reason:`综合价格、交期、技术与商务评分选定（综合分 ${q.totalScore}）`});await load()}})} async function saveInspection(){if(!selectedReceipt.value)return;await api.inspectGoodsReceipt(selectedReceipt.value.id,{...inspectForm});inspectOpen.value=false;message.success('质检完成，合格数量已入库并生成应付');await load()} async function saveInvoice(){invoiceForm.clientRequestId=`invoice-${Date.now()}`;await api.createSupplierInvoice({...invoiceForm});invoiceOpen.value=false;message.success('发票已登记，等待审核');await load()} async function reviewInvoice(x:api.SupplierInvoice,decision:'APPROVED'|'REJECTED'){await api.reviewSupplierInvoice(x.id,{decision,reviewerName:auth.user?.displayName||'审核人',comment:decision==='APPROVED'?'四单匹配审核通过':'发票审核驳回'});await load()} async function saveResolution(){if(!selectedReturn.value)return;await api.resolveProcurementReturn(selectedReturn.value.id,{...resolveForm});resolveOpen.value=false;message.success('退换货/索赔已结案');await load()}
function money(v:number){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY'}).format(Number(v||0))}
</script>
